### PR TITLE
OpenGLフロントエンド OpenGL frontend

### PR DESCRIPTION
**Pull request by terminal625**
- Scrolling
- Some mouse
- At least same as ncurses
Video:
- スクロール

- 一部のマウス

少なくともncursesと同じ

ビデオ：
[lem opengl](https://www.youtube.com/watch?v=JgUADI7axC8)

### CODE REVIEW

**Comment by snmsts** [comment]
Would you support rendering non ascii codes?

**Comment by terminal625** [comment]
I'll try to get Unicode working. It seems possible, but it might be harder than I expect.
私はUnicodeを実行しようとします。それは可能ですが、私が期待するよりも難しいかもしれません。

**Comment by snmsts** [comment]
FYI https://github.com/tamamu/glisph

**Comment by terminal625** [comment]
[glisph](https://github.com/tamamu/glisph) looks good. Unicode is difficult. I'll have to make major changes.
[glisph]（https://github.com/tamamu/glisph）は素晴らしいです。 Unicodeは困難です。私は大きな変更を加える必要があります。

**Comment by snmsts** [comment]
I'm sorry to make you feel need to translate to Japanese.
We would like to keep github using English as much as possible,
so sometimes we discuss in Japanese in person and that our decision looks take time.

I don't think you need to translate.
We talked about frontend contribution and we have some conversation.

* We afraid keeping frontend without maintainer.
* Editor hacking require long term patience to make it stable.
* Sucle is not quicklisp ready.
* Most of japanese depend on locale/unicode feature to use.

etc.. 

if you'd like to keep on hacking opengl frontend.
We'll invite you as collaborator and prepare open-gl branch for you.

**Comment by terminal625** [comment]
I'm sorry for rudely requesting OpenGL frontend, sorry for using ascii, sorry for opening this pull request without asking you, and sorry for trying to translate to Japanese.
- Why are you afraid of keeping frontend without maintainer? Many open source projects have no maintainer.
- How many years will you hack on lem?
- sucle can be changed with quicklisp ready [cl-bodge](https://github.com/borodust/cl-bodge) 
- Would a Japanese speaker help with open-gl branch?

Sorry for asking so many questions. 
Lem could benefit in popularity from open-gl frontend, which could increase users and make maintaining lem easier. I can hack on opengl frontend and contribute with [glisph](https://github.com/tamamu/glisph) in open-gl branch if you like. But I do not know Japanese. Also, if you abandon lem, I will also abandon lem.

**Comment by snmsts** [comment]
Every contribution is welcomed.Don't be sorry. I don't feel any rude on you at all.why ask before pull request? If you feel rude from me, I'm sorry advance.I don't intend to.

answering questions each.
* Once we merge code. we should have responsibility on the code. frontend would be changing along with backend and if no maintainer take care of it. We should discard it someday. it is painful decision.It may be not afraid hesitate. Sorry for bad English.  
* as long as I can code.(10 years? not sure) Practically never for a while.
* quicklisp ready is not requirement but if so we can feel it's stable.(at least it can be build ready with new environment.)
* I can't assure.Almost everyone using ncurses frontend. We have to take time to get use to or try. and my main computer is chromebook. I don't try it yet.

FYI (sorry in japanese :) )
https://gist.github.com/Hamayama/71ba25e9567b64ca855a5b8f7439add5

**Pull request closed without merging**
