### PR TITLE
Replace lem-setlocale with cl-setlocale

### PR DESCRIPTION
**Pull request by shamazmazum**
Hello! lem displays Russian text incorrectly on FreeBSD because LC_ALL is incorrectly defined in lem-setlocale. Rather than defining locale categories manually for all imaginable platforms I wrote cl-setlocale which uses cffi-grovel to pick them up from locale.h header (with exception for Windows).

It works for Linux, FreeBSD and Windows. Must work on macos too, but I am not sure (cl-travis does not support macos).

cl-setlocale is included in this patch under 2-clause BSD license because I have written it today and therefore it's not in quicklisp yet. I can change the license to whatever you want.

### CODE REVIEW

**Comment by cxxxr** [comment]
Sorry it took me so long to reply.
It looks like it's going to be registered with [quicklisp](https://github.com/quicklisp/quicklisp-projects/issues/1887), I think it's better to use it without bundling the source code of the cl-setlocale.

**Comment by shamazmazum** [comment]
Force-pushed to my development branch, so you will be able to merge this PR after cl-setlocale is available in quicklisp. Strange that CI tests have passed, though.

**Comment by cxxxr** [comment]
Thank you.
I'll merge this PR when quicklisp is updated.

CI tests is incomplete because it doesn't cover everything.

**Comment by shamazmazum** [comment]
cl-setlocale is in quicklisp now

**Comment by Hamayama** [comment]
constants-win32.lisp missing?
https://github.com/shamazmazum/cl-setlocale/tree/master/src

**Comment by shamazmazum** [comment]
> constants-win32.lisp missing?
> https://github.com/shamazmazum/cl-setlocale/tree/master/src

Oh, that's my fuckup. I forgot to push to master, sorry. Now it's fixed, but windows users will have to wait for another month. (or clone cl-setlocale locally)

This makes me sad (((

**Pull request merged**
