### PR TITLE
Support building without Roswell

### PR DESCRIPTION
**Pull request by Ambrevar**
As discussed in #412.

### CODE REVIEW

**Comment by cxxxr** [comment]
How about [this](https://github.com/cxxxr/lem/blob/master/build.lisp)?

**Comment by Ambrevar** [comment]
Works for me! :)

What about removing `build.lisp` and replacing it with a simple Makefile:

```
all:
    sbcl --eval '(asdf:make :lem/executable)' --quit
```

By the way, if you want to enable binary compression from the .asd, you can add the following method:

```lisp
#+sb-core-compression
(defmethod asdf:perform ((o asdf:image-op) (c asdf:system))
  (uiop:dump-image (asdf:output-file o c) :executable t :compression t))
```

**Comment by snmsts** [comment]
if you don't have problem, May I ask closing this pr @Ambrevar ?

**Comment by Ambrevar** [comment]
Can we either add the Makefile I mentioned or the `sbcl --eval ` line to the README?

**Comment by snmsts** [comment]
ah, I see

```
all-sbcl:
    sbcl --eval '(asdf:make :lem/executable)' --quit
```

for Makefile 

```
#+sb-core-compression
(defmethod asdf:perform ((o asdf:image-op) (c asdf:system))
  (uiop:dump-image (asdf:output-file o c) :executable t :compression t))
```

for asd right?

**Comment by Ambrevar** [comment]
Yes, the .asd trick is unrelated, but it's nice nonetheless!

**Comment by snmsts** [comment]
#422 to support this issue. thank you

**Pull request closed without merging**
