### PR TITLE
Now lem-version command output a git hash if it is available.

### PR DESCRIPTION
**Pull request by svetlyak40wt**
This should close issue #369.

### CODE REVIEW

**Comment by snmsts** [comment]
the git hash should be fixed when the source code is compiled,not the value of when the ``get-git-hash`` is called.

**Comment by svetlyak40wt** [comment]
Is it ok to get this information at compile time in the ASD file?


чт, 28 мар. 2019 г., 9:48 SANO,Masatoshi notifications@github.com:

**Comment by snmsts** [comment]
define-compiler-macro ?

**Comment by svetlyak40wt** [comment]
I never used it before and would like to know more about compiler macroses.

чт, 28 мар. 2019 г., 14:33 SANO,Masatoshi notifications@github.com:

**Comment by cxxxr** [comment]
Thank you.
I will fix that problem after merging.

**Pull request merged**
